# Generated by Django 5.0.7 on 2024-07-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("quantity", models.IntegerField()),
                ("category", models.CharField(max_length=255)),
                ("warehouse", models.CharField(max_length=255)),
                ("batch_number", models.CharField(max_length=50)),
                ("expiry_date", models.DateField()),
            ],
        ),
    ]
