# Generated by Django 5.0.7 on 2024-07-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="customer",
            new_name="Customer",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="customer",
            new_name="Customer",
        ),
        migrations.AddField(
            model_name="customer",
            name="contact",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
