# Generated by Django 5.0.7 on 2024-07-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="customer_email",
        ),
    ]
