from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', views.admin_dashboard, name='admin_dashboard'),
    path('invoices/', views.manage_invoices, name='manage_invoices'),
    path('invoices/new/', views.create_invoice, name='create_invoice'),
    path('invoices/<int:pk>/edit/', views.edit_invoice, name='edit_invoice'),
    path('invoices/<int:pk>/delete/', views.delete_invoice, name='delete_invoice'),
    path('inventory/', ManageInventoryView.as_view(), name='manage_inventory'),
    path('inventory1/', views.manage_inventory, name='manage_inventory'),
    path('inventory/new/', views.add_product, name='add_product'),
    path('inventory/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('inventory/<int:pk>/delete/', views.delete_product, name='delete_product'),
    path('expenses/', views.manage_expenses, name='manage_expenses'),
    path('expenses/new/', views.add_expense, name='add_expense'),
    path('expenses/<int:pk>/edit/', views.edit_expense, name='edit_expense'),
    path('expenses/<int:pk>/delete/', views.delete_expense, name='delete_expense'),
    path('reports/', views.reports, name='reports'),
    path('gst_reports/', views.manage_gst_reports, name='manage_gst_reports'),
    path('payments/', views.manage_payments, name='manage_payments'),
    path('payments/new/', views.add_payment, name='add_payment'),
    path('payments/<int:pk>/edit/', views.edit_payment, name='edit_payment'),
    path('payments/<int:pk>/delete/', views.delete_payment, name='delete_payment'),
    path('settings/', views.settings, name='settings'),
    path('vendors/', views.manage_vendors, name='manage_vendors'),
    path('vendors/new/', views.add_vendor, name='add_vendor'),
    path('vendors/<int:pk>/edit/', views.edit_vendor, name='edit_vendor'),
    path('vendors/<int:pk>/delete/', views.delete_vendor, name='delete_vendor'),
    path('parties', views.manage_parties, name='manage_parties'),
    path('Customers/', views.manage_Customers, name='manage_Customers'),
    path('Customers/new/', views.add_Customer, name='add_Customer'),
    path('Customers/<int:pk>/edit/', views.edit_Customer, name='edit_Customer'),
    path('Customers/<int:pk>/delete/', views.delete_Customer, name='delete_Customer'),
]
"""     path('users/', views.manage_users, name='manage_users'),
    path('users/new/', views.add_user, name='add_user'),
    path('users/<int:pk>/edit/', views.edit_user, name='edit_user'),
    path('users/<int:pk>/delete/', views.delete_user, name='delete_user'), """